"""AI service module for the AI LMS backend.

This module houses operations for processing user chat queries, constructing
personalized study plans, suggesting course recommendations, and logging usage.
"""

import time
import uuid
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ai_logs import AIUsageLog, ChatHistory
from app.schemas.ai import StudyPlanResponse, StudyTaskSchema, RecommendationsResponse, RecommendationSchema


class AIService:
    """AI Tutor chat and personalized recommendations generation services."""

    @staticmethod
    async def generate_chat_response(
        db: AsyncSession,
        user_id: uuid.UUID,
        course_id: uuid.UUID,
        message: str
    ) -> str:
        """Processes tutor chat messages, logs usage metrics, and stores chat history.

        Args:
            db (AsyncSession): Active database session.
            user_id (uuid.UUID): Student User ID.
            course_id (uuid.UUID): Reference Course UUID.
            message (str): Plain-text prompt string query.

        Returns:
            str: Graded/retrieved answer text generated by the tutor.
        """
        user_uuid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        course_uuid = uuid.UUID(str(course_id)) if not isinstance(course_id, uuid.UUID) else course_id
        start_time = time.time()

        # Save user message to database history
        user_message_record = ChatHistory(
            user_id=user_uuid,
            course_id=course_uuid,
            sender="user",
            message=message
        )
        db.add(user_message_record)

        # Generate intelligent contextual mock reply
        msg_lower = message.lower()
        if "rag" in msg_lower or "index" in msg_lower or "llama" in msg_lower:
            reply = (
                "RAG (Retrieval-Augmented Generation) connects LLMs to your private data. "
                "In LlamaIndex, we load documents, parse them into nodes, and build "
                "VectorStoreIndexes to yield highly relevant semantic matches before query completion."
            )
        elif "langgraph" in msg_lower or "agent" in msg_lower or "state" in msg_lower:
            reply = (
                "LangGraph is a stateful orchestration library that model loops "
                "and cyclic relationships in multi-agent workflows. It maps nodes "
                "as Python operations and edges as transitions that mutate shared State dictionaries."
            )
        elif "fastapi" in msg_lower or "route" in msg_lower or "async" in msg_lower:
            reply = (
                "FastAPI uses ASGI (Asynchronous Server Gateway Interface) standards to "
                "handle requests non-blockingly. By declaring async route handlers and "
                "leveraging asyncpg, we optimize database concurrency during token verification."
            )
        else:
            reply = (
                f"I received your query: '{message}'. As your AI Tutor, I have analysed your "
                "course catalog and active progress. Let me know if you would like me to "
                "generate practice quizzes, explain complex sections, or update your study plan."
            )

        # Save assistant message to database history
        assistant_message_record = ChatHistory(
            user_id=user_uuid,
            course_id=course_uuid,
            sender="assistant",
            message=reply
        )
        db.add(assistant_message_record)

        # Calculate log variables
        latency_ms = int((time.time() - start_time) * 1000)
        tokens_spent = len(message.split()) + len(reply.split())

        # Save usage log
        usage_log = AIUsageLog(
            user_id=user_uuid,
            action="chat",
            tokens_used=tokens_spent,
            latency_ms=max(1, latency_ms)
        )
        db.add(usage_log)

        await db.commit()
        return reply

    @staticmethod
    async def generate_study_plan(db: AsyncSession, user_id: uuid.UUID) -> StudyPlanResponse:
        """Constructs personalized daily study milestones.

        Args:
            db (AsyncSession): Active database session.
            user_id (uuid.UUID): Student User ID.

        Returns:
            StudyPlanResponse: Container holding daily task milestones.
        """
        user_uuid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        start_time = time.time()

        tasks = [
            StudyTaskSchema(
                task="Complete the quiz on 'FastAPI Dependency Injection'",
                duration="15 mins"
            ),
            StudyTaskSchema(
                task="Watch the 'LlamaIndex Storage Context' lesson video",
                duration="20 mins"
            ),
            StudyTaskSchema(
                task="Ask the AI Tutor to clarify 'LangGraph Cycles and Recursion'",
                duration="10 mins"
            )
        ]

        # Log AI Usage
        latency_ms = int((time.time() - start_time) * 1000)
        usage_log = AIUsageLog(
            user_id=user_uuid,
            action="study_plan",
            tokens_used=120,
            latency_ms=max(1, latency_ms)
        )
        db.add(usage_log)
        
        await db.commit()
        return StudyPlanResponse(tasks=tasks)

    @staticmethod
    async def generate_course_recommendations(
        db: AsyncSession,
        user_id: uuid.UUID
    ) -> RecommendationsResponse:
        """Suggests appropriate learning paths based on current skills.

        Args:
            db (AsyncSession): Active database session.
            user_id (uuid.UUID): Student User ID.

        Returns:
            RecommendationsResponse: List of course recommendation cards.
        """
        user_uuid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        start_time = time.time()

        # These match the UUIDs of the seeded courses
        recs = [
            RecommendationSchema(
                id=uuid.UUID("e4b3c004-94c6-47b2-84c1-cd54cfc0bf7a"),
                title="Python Programming Basics",
                description="Master variables, collections, loops, and OOP concepts in Python.",
                duration="5.5 hrs",
                difficulty="Beginner"
            ),
            RecommendationSchema(
                id=uuid.UUID("9d3f82a1-fa4c-4a30-8a8b-3e5f2a1b1c3c"),
                title="Building RAG Pipelines with LlamaIndex",
                description="Learn index construction, vector retrieval models, and contextual LLM generation.",
                duration="4.5 hrs",
                difficulty="Intermediate"
            ),
            RecommendationSchema(
                id=uuid.UUID("8b3f92d4-fc3a-4a25-9b2c-4f5f8b9b2c2d"),
                title="Multi-Agent Coordination with LangGraph",
                description="Master state graphs, cognitive agent routing loops, and human-in-the-loop triggers.",
                duration="6.0 hrs",
                difficulty="Advanced"
            )
        ]

        # Log AI Usage
        latency_ms = int((time.time() - start_time) * 1000)
        usage_log = AIUsageLog(
            user_id=user_uuid,
            action="recommendations",
            tokens_used=180,
            latency_ms=max(1, latency_ms)
        )
        db.add(usage_log)
        
        await db.commit()
        return RecommendationsResponse(recommendations=recs)
