"""AI schemas for validating tutor chat interactions and personalized recommendations.

This module houses validation models for sending user prompts, returning chatbot replies,
formatting daily study plans, and recommending courses.
"""

from typing import List
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Schema representing user prompt messages.

    Attributes:
        message (str): Plain-text prompt string.
    """
    message: str = Field(..., min_length=1, description="User's query string sent to AI Tutor")


class ChatResponse(BaseModel):
    """Schema representing tutor reply responses.

    Attributes:
        reply (str): Text response generated by AI.
    """
    reply: str = Field(..., description="Response reply text from AI Tutor")


class StudyTaskSchema(BaseModel):
    """Schema representing one daily study plan task milestone.

    Attributes:
        task (str): Task description.
        duration (str): Milestone timing.
    """
    task: str
    duration: str


class StudyPlanResponse(BaseModel):
    """Schema representing daily study task plans.

    Attributes:
        tasks (List[StudyTaskSchema]): List of milestones.
    """
    tasks: List[StudyTaskSchema] = Field(default=[])


class RecommendationSchema(BaseModel):
    """Schema representing one AI recommended course structure.

    Attributes:
        id (str): Reference Course slug ID.
        title (str): Course name.
        description (str): Explanatory summary.
        duration (str): Approximate timing.
        difficulty (str): Syllabus difficulty level.
    """
    id: str
    title: str
    description: str
    duration: str
    difficulty: str


class RecommendationsResponse(BaseModel):
    """Schema representing a list of custom course recommendations.

    Attributes:
        recommendations (List[RecommendationSchema]): Course recommendations.
    """
    recommendations: List[RecommendationSchema] = Field(default=[])
