"""FastAPI API Router module for the Multi-Agent System.

Exposes SSE streaming chat endpoints connected to the LangGraph execution flow.
"""

import sys
import json
import uuid
import structlog
from pathlib import Path
from typing import AsyncGenerator
from fastapi import APIRouter, Depends, Request, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from slowapi import Limiter
from slowapi.util import get_remote_address

# Configure sys.path to resolve root and backend directory imports
root_path = Path(__file__).parent.parent
backend_path = root_path / "backend"
if str(root_path) not in sys.path:
    sys.path.append(str(root_path))
if str(backend_path) not in sys.path:
    sys.path.append(str(backend_path))

from app.core.config import settings
from app.core.dependencies import get_db, get_current_user
from app.models.user import User
from app.schemas.base import ApiResponse
from app.schemas.ai import ChatRequest, StudyPlanResponse, RecommendationsResponse
from app.services.ai_service import AIService
from agents.graph import graph
from langchain_core.messages import HumanMessage, AIMessage

logger = structlog.get_logger()


from app.api.v1.routes.ai import limiter
router = APIRouter(prefix="/ai", tags=["AI Integration"])


@router.post("/chat")
@limiter.limit("10/minute")
async def chat(
    request: Request,
    body: ChatRequest,
    course_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Answers a course-related query by streaming LangGraph agent tokens via Server Sent Events (SSE).

    Args:
        request (Request): Mandatory request parameter for slowapi.
        body (ChatRequest): User question input.
        course_id (uuid.UUID): Reference Course UUID.
        current_user (User): Active student session.
        db (AsyncSession): Active database session.

    Returns:
        StreamingResponse: Chunked token stream using text/event-stream.
    """
    logger.info("sse_ai_chat_requested", user_id=current_user.id, course_id=course_id)

    async def sse_generator() -> AsyncGenerator[str, None]:
        thread_id = f"{current_user.id}_{course_id}"
        config = {
            "configurable": {
                "thread_id": thread_id,
                "db": db
            }
        }

        # 1. Load current graph execution state
        state = await graph.aget_state(config)

        # 2. Check for human-in-the-loop validation checkpoints
        if state.next:
            logger.info("sse_resuming_graph_from_checkpoint", next_node=state.next)
            # Update state with the user's decision (approve/reject message) and resume
            await graph.aupdate_state(config, {"messages": [HumanMessage(content=body.message)]})
            event_stream = graph.astream_events(None, config, version="v2")
        else:
            logger.info("sse_starting_new_graph_turn")
            input_state = {
                "messages": [HumanMessage(content=body.message)],
                "user_id": str(current_user.id),
                "course_id": str(course_id),
                "context": [],
                "error": None
            }
            event_stream = graph.astream_events(input_state, config, version="v2")

        # 3. Stream graph node execution and chat model tokens
        try:
            async for event in event_stream:
                kind = event.get("event")
                name = event.get("name")

                # Stream token increments generated by the active model
                if kind == "on_chat_model_stream":
                    content = event.get("data", {}).get("chunk", {}).content or ""
                    if content:
                        yield f"data: {json.dumps({'type': 'token', 'content': content})}\n\n"

                # Stream node state transitions
                elif kind == "on_chain_start" and name in ("tutor", "quiz_generator", "path_advisor", "orchestrator"):
                    yield f"data: {json.dumps({'type': 'agent_start', 'agent': name})}\n\n"
                elif kind == "on_chain_end" and name in ("tutor", "quiz_generator", "path_advisor", "orchestrator"):
                    yield f"data: {json.dumps({'type': 'agent_end', 'agent': name})}\n\n"

        except Exception as e:
            logger.error("sse_stream_execution_error", error=str(e))
            yield f"data: {json.dumps({'type': 'error', 'content': f'Stream execution failure: {str(e)}'})}\n\n"

        # 4. Check post-execution state for human interrupts
        post_state = await graph.aget_state(config)
        if post_state.next:
            logger.info("sse_graph_suspended_on_interrupt", next_node=post_state.next)
            quiz_data = post_state.values.get("quiz_data")
            yield f"data: {json.dumps({'type': 'interrupt', 'message': 'Quiz review requested', 'quiz_data': quiz_data})}\n\n"

    return StreamingResponse(sse_generator(), media_type="text/event-stream")


@router.get("/study-plan", response_model=ApiResponse[StudyPlanResponse])
@limiter.limit("10/minute")
async def get_study_plan(
    request: Request,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Generates personalized study task milestones.

    Args:
        request (Request): Mandatory request context.
        current_user (User): Graded User session.
        db (AsyncSession): Active database session.

    Returns:
        ApiResponse[StudyPlanResponse]: Standardized study milestones.
    """
    logger.info("ai_study_plan_requested", user_id=current_user.id)
    plan = await AIService.generate_study_plan(db, current_user.id)
    return ApiResponse(
        success=True,
        data=plan,
        message="AI study plan generated successfully"
    )


@router.get("/recommendations", response_model=ApiResponse[RecommendationsResponse])
@limiter.limit("10/minute")
async def get_recommendations(
    request: Request,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Recommends courses matching the user profile skills.

    Args:
        request (Request): Mandatory request context.
        current_user (User): Graded User session.
        db (AsyncSession): Active database session.

    Returns:
        ApiResponse[RecommendationsResponse]: Standardized course recommendations list.
    """
    logger.info("ai_recommendations_requested", user_id=current_user.id)
    recs = await AIService.generate_course_recommendations(db, current_user.id)
    return ApiResponse(
        success=True,
        data=recs,
        message="AI recommendations generated successfully"
    )
